#!/bin/zsh
test "$1" = "" && {
    echo "Oh, my Gog! You didn't type directory's name with goddamn spaces! Please type directory"
    exit 1 }
oldIFS=$IFS
IFS='
'
for C in `find ~/$1 -maxdepth 1 -type f -iname "*[а-я]*"`; do
    mv $C `echo "$C" | sed 's/\([а-я]\)/ru_\1/1'`
done
IFS=$oldIFS
echo "The operation to destroying all spaces is successfull, commander!"
