#!/bin/zsh
test "$1" = "" && {
    echo "Oh, my Gog! You didn't type directory's name with goddamn spaces! Please type directory"
    exit 1 }
oldIFS=$IFS
IFS='
'
for C in `find ./ -maxdepth 1 -type f -iname "* *"`; do
    mv $C `echo $C | sed s/' '/_/g`
done
IFS=$oldIFS
echo "The operation to destroying all spaces is successfull, commander!"
